<!DOCTYPE html>
<html lang="es">
 <head>
  <meta http-equiv='Content-type' content='text/html; charset=<?php echo APP_CHARSET ?>' />
  <title>APLICACION PARA CONTABILIZAR LOS VOTOS CHAVISTAS</title>
  <!-- <?php Tag::css('bienvenida') ?> -->
  <!-- <?php Tag::css('style') ?> -->
  <?php Tag::css('bootstrap/bootstrap') ?>
  <?php echo Html::includeCss() ?>

</head>
<body>

<div class="container">
  <?php View::partial('inicio/navbar') ?>
  <?php View::content(); ?>
  <?php View::partial('inicio/footer') ?>
</div>
</body>
</html>
<?php echo Tag::js('jquery/jquery.min') ?>
<?php echo Tag::js('bootstrap/bootstrap') ?>
