<!DOCTYPE html>
<html lang="es">
 <head>
  <meta http-equiv='Content-type' content='text/html; charset=<?php echo APP_CHARSET ?>' />
  <title>|:. SISTEMA PARA EL CONTROL DE LAS IMPRESORAS .:|</title>
  <!-- <?php Tag::css('bienvenida') ?> -->
  <!-- <?php Tag::css('style') ?> -->
  <?php Tag::css('bootstrap/bootstrap') ?>
  <?php echo Html::includeCss() ?>

</head>
<body>

		<?php View::partial('inicio/navbar') ?>
<div class="container">
	<!-- <div class="row"> -->
	<!-- </div> -->
	<!-- <div class="row"> -->
		<?php View::content("cuerpo"); ?>
	<!-- </div> -->
	<!-- <div class="row"> -->
	<!-- </div> -->
</div>
		<?php View::partial('inicio/footer') ?>
</body>
</html>
<?php echo Tag::js('jquery/jquery.min') ?>
<?php echo Tag::js('bootstrap/bootstrap') ?>
