<!DOCTYPE html>
<html lang="es">
 <head>
  <meta http-equiv='Content-type' content='text/html; charset=<?php echo APP_CHARSET ?>' />
  <title>APLICACION PARA CONTABILIZAR LOS VOTOS CHAVISTAS</title>
  <?php Tag::css('bienvenida') ?>
  <?php Tag::css('style') ?>
  <?php Tag::css('bootstrap') ?>
  <?php echo Html::includeCss() ?>

  <?php echo Tag::js('bootstrap') ?>
</head>
<body>
<div class="container">
    <?php View::partial('psuv/top') ?>
        <?php View::content(); ?>

    <?php View::partial('psuv/footer') ?>
</div>
<!--     <div id='content'>
        <div id='head'>
            <div class='alignright'>
                <p id='config'>
                    <span class='app'><?php echo basename(dirname(APP_PATH)) ?></span>
                    <?php echo Html::link('pages/show/kumbia/status/', 'Config', 'title="Ver configuración de la aplicación"') ?>
                </p>
             </div>
             
            <h1 id='logo'>KumbiaPHP</h1>
            <h2 id='info-app'>web &amp; app Framework versión <?php echo kumbia_version() ?></h2>
        </div>


    </div> -->
</body>
</html>
