<!-- Menu Superior -->
<!-- Esta seccion espara dispositivos moviles y tabletas -->
<div id="menu" class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">||INCES FALCON||</a>
    </div>
    <!-- Inicio del menu -->
    <div class="navbar-collapse collapse">
    <!-- Mutilnivel -->
      <ul class="nav navbar-nav">
        <li><a href="#">Inicio</a></li>
        <li><a href="#">Consulta</a></li>
        <!-- <li><a href="#contact">Galeria de imagenes</a></li> -->
        <!-- <li><a href="#" id="consulta">Consulta de saldo</a></li> -->
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Acceso</a></li>
      </ul>
    </div>
    <!--/.nav-collapse -->
  </div>
</div>